# Generated by Django 5.1.6 on 2025-02-27 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lost', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='telegram_contact',
            field=models.CharField(default=None, help_text='Введите ссылку на ваш Telegram', max_length=255),
            preserve_default=False,
        ),
    ]
